logbook:
  exclude:
    - \*swagger\*
    - swagger-ui.html\*
    - \*\*/api-docs
    - \*\*/api-docs/\*\*

logging:
  level:
    org:
      hibernate:
        sql: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true